export const madeira = {
    bruta: [
        "CCCCCCPPP",
        "PPPPPPPPP",
        "PIPPIPPPP",
        "PPPPPPPPP",
        "PPPPPPPPP",
    ],
    refinada: [
        "CCCCCCPPP",
        "PPPPPPPPP",
        "PIPPIPPPP",
        "PPPPPPPPP",
        "PPPPPPPPP",
    ],
}
export const boneco = {
    "frente": [[
        "   CCCC   ",
        "  CCCCCC  ",
        "  PPPPPP  ",
        "  PIPPIP  ",
        "  PPPPPP  ",
        "    PP    ",
        "  PRRRRP  ",
        "  PRRRRR  ",
        "  RRRRRR  ",
        "  KK  KK  ",
        "  KK  KK  ",],
    [
        "   CCCC   ",
        "  CCCCCC  ",
        "  PPPPPP  ",
        "  PIPPIP  ",
        "  PPPPPP  ",
        "    PP    ",
        "  PRRRRP  ",
        "  RRRRRP  ",
        "  RRRRRR  ",
        "  KK  KK  ",
        "  KK  KK  ",]],

    "costas": [
        "   CCCC   ",
        "  CCCCCC  ",
        "  PPPPPP  ",
        "  PPPPPP  ",
        "  PPPPPP  ",
        "    PP    ",
        "  RRRRRR  ",
        "  RRRRRR  ",
        "  RRRRRR  ",
        "  KK  KK  ",
        "  KK  KK  ",
    ],

    "esquerda": [
        "    C     ",
        "    CC    ",
        "    PP    ",
        "    IP    ",
        "    PP    ",
        "    PP    ",
        "    RR    ",
        "    RR    ",
        "    RR    ",
        "    KK    ",
        "   KKK    ",
    ],

    "direita": [
        "    C     ",
        "    CC    ",
        "    PP    ",
        "    PI    ",
        "    PP    ",
        "    PP    ",
        "    RR    ",
        "    RR    ",
        "    RR    ",
        "    KK    ",
        "    KKK   ",
    ]
};
export const arvore = {
    padrao: [

        "          ",
        "          ",
        "          ",
        "          ",
        "  FFFFFF  ",
        "  FFFFFF  ",
        " FFFFFFFF ",
        " FFFFFFFF ",
        " FFFFFFFF ",
        " OOOOOOOO ",
        "    TT    ",
        "    TT    ",
        "    TT    ",
        "    TT    ",
        "    TT    ",
    ],
    interacao: [
        "  IIIIII  ",
        "  IBBBBI  ",
        "  IBIIII  ",
        "  IBBBBI  ",
        "  IBIIII  ",
        "  IBBBBI  ",
        " FIIIIIIF ",
        " FFFFFFFF ",
        " FFFFFFFF ",
        " OOOOOOOO ",
        "    TT    ",
        "    TT    ",
        "    TT    ",
        "    TT    ",
        "    TT    ",
    ]
}