export const arvore = {
padrao:[
"          ",
"          ",
"          ",
"          ",
"  FFFFFF  ",
"  FFFFFF  ",
" FFFFFFFF ",
" FFFFFFFF ",
" FFFFFFFF ",
" OOOOOOOO ",
"    TT    ",
"    TT    ",
"    TT    ",
"    TT    ",
"    TT    ",
],
interacao : [
"  IIIIII  ",
"  IBBBBI  ",
"  IBIIII  ",
"  IBBBBI  ",
"  IBIIII  ",
"  IBBBBI  ",
" FIIIIIIF ",
" FFFFFFFF ",
" FFFFFFFF ",
" OOOOOOOO ",
"    TT    ",
"    TT    ",
"    TT    ",
"    TT    ",
"    TT    ",
]
}